/// Flutter icons PTB_go_icon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PTB_go_icon
///      fonts:
///       - asset: fonts/PTB_go_icon.ttf
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ShwelarIcons {
  ShwelarIcons._();

  static const _kFontFam = 'PTB_go_icon';
  static const _kFontPkg = null;

  static const IconData visibility =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibilityOff =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
